server.port=8080

spring.application.name=banking-system

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

app.jwt.secret=change-this-secret-to-at-least-32-characters
app.jwt.expiration-ms=86400000
